# Generated by Django 5.0.1 on 2024-05-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseprofile',
            name='email',
        ),
    ]
