# Generated by Django 5.0.1 on 2024-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_remove_franchiseprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseprofile',
            name='purse_money',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=20),
        ),
    ]
