# Generated by Django 5.0.1 on 2024-05-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0007_alter_franchiseprofile_purse_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseprofile',
            name='purse_money',
        ),
    ]
