# Generated by Django 5.0.1 on 2024-11-01 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0010_alter_franchiseprofile_purse_money'),
        ('players', '0004_alter_playerprofile_current_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purse', models.DecimalField(decimal_places=0, default=None, max_digits=30, null=True)),
                ('original_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_entries', to='franchise.franchiseprofile')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_franchises', to='auctioneer.liveauction')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=0, default=None, max_digits=15, null=True)),
                ('team', models.CharField(default=None, max_length=20, null=True)),
                ('interested_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_in', to='auctioneer.auctionfranchise')),
                ('original_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_entries', to='players.playerprofile')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_players', to='auctioneer.liveauction')),
            ],
        ),
    ]
