# Generated by Django 5.0.1 on 2024-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0002_liveauction_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionplayer',
            name='interested_team',
        ),
        migrations.AddField(
            model_name='auctionplayer',
            name='interested_team',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_in', to='auctioneer.auctionfranchise'),
        ),
    ]
