# Generated by Django 5.0.1 on 2025-01-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioneer', '0003_remove_auctionplayer_interested_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionfranchise',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='auctionplayer',
            name='auction',
        ),
        migrations.AddField(
            model_name='liveauction',
            name='auction_franchises',
            field=models.ManyToManyField(blank=True, related_name='auctions_bidding_for', to='auctioneer.auctionfranchise'),
        ),
        migrations.AddField(
            model_name='liveauction',
            name='auction_players',
            field=models.ManyToManyField(blank=True, related_name='auctions_participated_in', to='auctioneer.auctionplayer'),
        ),
        migrations.AddField(
            model_name='liveauction',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_in', to='auctioneer.auctionplayer'),
        ),
        migrations.AddField(
            model_name='liveauction',
            name='current_team_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_team_bid_in', to='auctioneer.auctionfranchise'),
        ),
        migrations.AddField(
            model_name='liveauction',
            name='leading_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_bidder_in', to='auctioneer.auctionfranchise'),
        ),
        migrations.AlterField(
            model_name='auctionfranchise',
            name='purse',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='auctionplayer',
            name='bid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='auctionplayer',
            name='interested_team',
            field=models.ManyToManyField(blank=True, related_name='interested_in', to='auctioneer.auctionfranchise'),
        ),
        migrations.AlterField(
            model_name='auctionplayer',
            name='team',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
