# Generated by Django 5.0.1 on 2024-05-18 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('native', models.CharField(choices=[('Indian', 'Indian'), ('overseas', 'Overseas')], max_length=10)),
                ('role', models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('all_rounder', 'All rounder')], max_length=20)),
                ('batting_style', models.CharField(choices=[('right handed', 'Right handed'), ('left handed', 'Left handed'), ('NULL', 'None')], max_length=20)),
                ('bowling_style', models.CharField(choices=[('right arm fast', 'Right arm fast'), ('right arm medium', 'Right arm medium'), ('right arm spin', 'Right arm spin'), ('left arm fast', 'Left arm fast'), ('left arm medium', 'Left arm medium'), ('left arm spin', 'Left arm spin'), ('NULL', 'None')], max_length=20)),
                ('dob', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
