# Generated by Django 5.0.1 on 2024-05-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='last_name',
        ),
    ]
